version: '3.9'

services:
  django:
    build: .
    container_name: django
    command:
          - tree
          - python manage.py makemigrations
          - python manage.py migrate
          - coverage run --source='.' manage.py test 
          - python manage.py runserver 0.0.0.0:8000
                   
    ports:
      - "8000:8000"